const { createApp } = Vue;

createApp({
    data() {
        return {
            friendsDetails: [
                {
                    id: 1,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-01.jpg",
                    name: "Amir Ashraf",
                    jop: "Front-End Developer",
                    friends: "99 Friend",
                    projects: "15 Projects",
                    articles: "25 Articles",
                    join: "Joined 02/10/2021",
                    profile: "Profile",
                    remove: "Remove"
                },
                {
                    id: 2,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-02.jpg",
                    name: "Mahmoud Ashraf",
                    jop: "Cloud Developer",
                    friends: "30 Friend",
                    projects: "11 Projects",
                    articles: "12 Articles",
                    join: "Joined 02/8/202",
                    profile: "Profile",
                    remove: "Remove"
                },
                {
                    id: 3,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-03.jpg",
                    name: "Amir Salah",
                    jop: "Mobile Developer",
                    friends: "80 Friend",
                    projects: "20 Projects",
                    articles: "18 Articles",
                    join: "Joined 02/6/2020",
                    profile: "Profile",
                    remove: "Remove"
                },
                {
                    id: 4,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-04.jpg",
                    name: "Ahmed Adel",
                    jop: "Back-End Developer",
                    friends: "70 Friend",
                    projects: "30 Projects",
                    articles: "18 Articles",
                    join: "Joined 28/06/2020",
                    profile: "Profile",
                    remove: "Remove"
                },
                {
                    id: 5,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-05.jpg",
                    name: "Ayman Hekal",
                    jop: "Algorithm Developer",
                    friends: "80 Friend",
                    projects: "30 Projects",
                    articles: "18 Articles",
                    join: "Joined 02/10/2021",
                    profile: "Profile",
                    remove: "Remove"
                },
                {
                    id: 6,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-04.jpg",
                    name: "Khaled Mohamed",
                    jop: "Back-End Developer",
                    friends: "70 Friend",
                    projects: "30 Projects",
                    articles: "18 Articles",
                    join: "Joined 28/06/2020",
                    profile: "Profile",
                    remove: "Remove"
                },
                {
                    id: 7,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-02.jpg",
                    name: "Omar Tarek",
                    jop: "Cloud Developer",
                    friends: "30 Friend",
                    projects: "11 Projects",
                    articles: "12 Articles",
                    join: "Joined 02/8/202",
                    profile: "Profile",
                    remove: "Remove"
                },
                {
                    id: 8,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-03.jpg",
                    name: "Ahmed Ezzat",
                    jop: "Content Creator",
                    friends: "80 Friend",
                    projects: "30 Projects",
                    articles: "18 Articles",
                    join: "Joined 28/08/2020",
                    profile: "Profile",
                    remove: "Remove"
                },
                {
                    id: 9,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-04.jpg",
                    name: "Ali Omar",
                    jop: "JavaScript Developer",
                    friends: "90 Friend",
                    projects: "15 Projects",
                    articles: "25 Articles",
                    join: "Joined 02/10/2021",
                    profile: "Profile",
                    remove: "Remove"
                },
                {
                    id: 10,
                    phone: "fa-solid fa-phone",
                    Litter: "fa-regular fa-envelope",
                    img: "./imgs/friend-05.jpg",
                    name: "Ahmed Salah",
                    jop: "Front-End Developer",
                    friends: "80 Friend",
                    projects: "20 Projects",
                    articles: "18 Articles",
                    join: "Joined 02/06/2020",
                    profile: "Profile",
                    remove: "Remove"
                },
            ],
        };
    },
}).mount("#friends")